name: essis_env
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - r-base=4.3.3
  - r-devtools=2.4.5
  - r-usethis=2.2.3
  - r-htmlwidgets=1.6.4
  - r-plotly=4.10.4
  - r-ggplot2=3.5.1
  - r-reshape2=1.4.4
  - r-stringr=1.5.1
  - r-igraph=2.0.3
  - r-data.table=1.15.2
  - r-optparse=1.7.5
  - r-magrittr=2.0.3
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-plyr=1.8.9
  - r-jsonlite=1.8.8
  - r-xml2=1.3.6
  - r-lifecycle=1.0.4
  - r-vctrs=0.6.5
  - r-cli=3.6.2
  - r-tibble=3.2.1
  - r-purrr=1.0.2
  - r-getopt=1.20.4
  - r-getoptlong=1.0.5
  - r-rjson=0.2.21
  - r-cachem=1.0.8
  - r-progress=1.2.3
  - r-r6=2.5.1
  - r-glue=1.7.0
  - r-crayon=1.5.2
  - r-yaml=2.3.8
  - r-zoo=1.8-12
  - r-httr=1.4.7
  - r-rcurl=1.98-1.14
  - r-rcpp=1.0.12
  - r-lazyeval=0.2.2
  - r-fansi=1.0.6
  - r-blob=1.2.4
  - r-prettyunits=1.2.0
  - r-urlchecker=1.0.1
  - r-sessioninfo=1.2.2
  - r-pkgload=1.3.4
  - r-pkgbuild=1.4.4
  - r-remotes=2.5.0
  - r-pkgconfig=2.0.3
  - r-rcolorbrewer=1.1-3
  - r-colorspace=2.1-0
  - r-shape=1.4.6.1
  - r-circlize=0.4.16
  - r-gtable=0.3.5
  - r-xtable=1.8-4
  - r-munsell=0.5.1
  - r-png=0.1-8
  - r-ellipsis=0.3.2
  - r-dbplyr=2.5.0
  - r-clue=0.3-65
  - r-foreach=1.5.2
  - r-iterators=1.0.14
  - r-digest=0.6.35
  - r-hms=1.1.3
  - r-utf8=1.2.4
  - r-pillar=1.9.0
  - r-scales=1.3.0
  - r-viridislite=0.4.2
  - r-miniui=0.1.1.1
  - r-later=1.3.2
  - r-promises=1.3.0
  - r-httpuv=1.6.15
  - r-shiny=1.8.1.1
  - r-profvis=0.3.8
  - r-abind=1.4-5
  - r-filelock=1.0.3
  - r-rappdirs=0.3.3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-lattice=0.22-6
  - r-codetools=0.2-20

  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-s4vectors=0.40.2
  - bioconductor-iranges=2.36.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomicranges=1.54.1
  - bioconductor-genomicfeatures=1.54.1
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-variantannotation=1.48.1
  - bioconductor-rsamtools=2.18.0
  - bioconductor-biostrings=2.70.1
  - bioconductor-xvector=0.42.0
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-genomicalignments=1.38.0
  - bioconductor-annotationdbi=1.64.1
  - bioconductor-biomaRt=2.58.0
  - bioconductor-bsgenome=1.70.1
  - bioconductor-keggrest=1.42.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-delayedarray=0.28.0
  - bioconductor-biocfilecache=2.10.1
  - bioconductor-biocio=1.12.0
  - bioconductor-zlibbioc=1.48.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-genomeinfodbdata=1.2.11
